apiVersion: apps/v1
kind: Deployment
metadata:
 name: gunicorn
spec:
 selector:
   matchLabels:
    type: gunicorn
    app: backend
    version: ver:latest
 replicas: 1
 template:
   metadata:
     labels:
       type: gunicorn
       app: backend
       version: ver:latest
   spec:
    containers:
    - name: container
      image: conna/gunicorn:latest
      envFrom:
        - configMapRef:
            name: mysql-cm
        - secretRef:
            name: mysql-sec
      ports:
      - containerPort: 8000
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m